package application;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.MenuItem;
import javafx.stage.Stage;

public class CheckOutController {
	@FXML
	private MenuItem exit;

	// Event Listener on MenuItem[#exit].onAction
	@FXML
	public void exitProgram(ActionEvent event) {
		// TODO Autogenerated
	}
	 @FXML
	    private Button AdvSearch;
	    
	    @FXML
	    private Button Toplist;
	    
	    @FXML
	    private Button CheckOut;
	    
	     
	    @FXML
	    private Button GoBack;
	    
	    @FXML
	    private Button MyBooks;
	    
	
	@FXML
void GoBack(ActionEvent event) throws IOException {
	Parent  My_View_parent = FXMLLoader.load(getClass().getResource("MyView.fxml"));
	Scene My_View_scene = new Scene(My_View_parent);
	Stage app_stage  = (Stage) ((Node) event.getSource()).getScene().getWindow();
	app_stage.setScene(My_View_scene);
	app_stage.show();
}


@FXML
void AdvSearch(ActionEvent event) throws IOException {
	Parent Advanced_Search_parent = FXMLLoader.load(getClass().getResource("AdvancedSearch.fxml"));
	Scene Advanced_Search_scene = new Scene(Advanced_Search_parent);
	Stage app_stage  = (Stage) ((Node) event.getSource()).getScene().getWindow();
	app_stage.setScene(Advanced_Search_scene);
	app_stage.show();

}
@FXML
void EnterMyBorrowedBooks(ActionEvent event) throws IOException {
	Parent My_Books_parent = FXMLLoader.load(getClass().getResource("MyBooks.fxml"));
	Scene My_Books_scene = new Scene(My_Books_parent);
	Stage app_stage  = (Stage) ((Node) event.getSource()).getScene().getWindow();
	app_stage.setScene(My_Books_scene);
	app_stage.show();
}

@FXML
void GoToToplist(ActionEvent event) throws IOException {
	Parent Toplist_parent = FXMLLoader.load(getClass().getResource("Toplist.fxml"));
	Scene Toplist_scene = new Scene(Toplist_parent);
	Stage app_stage  = (Stage) ((Node) event.getSource()).getScene().getWindow();
	app_stage.setScene(Toplist_scene);
	app_stage.show();

}

@FXML
void GoToCheckOut(ActionEvent event)  throws IOException {
	Parent CheckOut_parent = FXMLLoader.load(getClass().getResource("CheckOut.fxml"));
	Scene CheckOut_scene = new Scene(CheckOut_parent);
	Stage app_stage  = (Stage) ((Node) event.getSource()).getScene().getWindow();
	app_stage.setScene(CheckOut_scene);
	app_stage.show();

}
}
